### ISSUE TITLE
Add set mader nigga timeout on this sht

### ISSUE THREAD

**Issue by fdc-markrickson** [Leir-bg/fe-tools-vs-ext#25]
https://gyazo.com/b16893c140351ae75a737d21af7c5f24

**Comment by FDC-gabriel** [comment]
:(

**Comment by FDC-gabriel** [comment]
Not possible, see issues
https://github.com/microsoft/vscode/issues/11858
https://github.com/microsoft/vscode/issues/12615

Suggested action:
- press escape a couple of times until messages disappear 🌧️

**Comment by FDC-gabriel** [comment]
added custom information message, check this PR
https://github.com/Leir-bg/fe-tools-vs-ext/pull/26

this will be included in the next version update 💪

**Comment by fdc-markrickson** [comment]
> added custom information message, check this PR #26
> 
> this will be included in the next version update 💪

push it now dont wait for next fucking update
